edit action for run container

diff --git a/.github/workflows/r.yml b/.github/workflows/r.yml
--- a/.github/workflows/r.yml
+++ b/.github/workflows/r.yml
@@ -12,9 +12,16 @@ jobs:
       - name: Checkout the repository
         uses: actions/checkout@v3
 
-      - name: Load and export variables from .env file
+      - name: Verify .env file exists
         run: |
-          export $(grep -v '^#' .env | xargs)
+          if [ ! -f .env ]; then echo ".env file not found"; exit 1; fi
+        shell: bash
+
+      - name: Load .env file
+        run: |
+          set -o allexport
+          source .env
+          set +o allexport
         shell: bash
 
       - name: Set up Docker
